// Auto-generated Custom Skills Bundle
// Generated at: 2026-01-31T19:13:52.838Z
// Total skills: 2

window.CUSTOM_SKILLS = {
  "deal-news": {
    "content": "---\r\nname: deal-news\r\ndescription: Deal 뉴스 자동 수집 - GitHub Actions 트리거 + 모니터링 + 결과 확인\r\nargument-hint: \"[날짜 YYYY-MM-DD]\"\r\nallowed-tools: \"Bash(gh *), Bash(cd *), Bash(sleep *), Read, Grep\"\r\n---\r\n\r\n# Deal News 자동 수집\r\n\r\n투자 뉴스를 자동으로 수집합니다. GitHub Actions 워크플로우를 트리거하고 결과를 확인합니다.\r\n\r\n## 프로세스\r\n\r\n### Step 1: 워크플로우 트리거\r\n\r\n날짜 인자가 있으면 해당 날짜, 없으면 어제 날짜로 수집합니다.\r\n\r\n```bash\r\n# 인자 있을 때\r\ngh workflow run \"Daily Investment News Scraper\" --ref master -f target_date=$ARGUMENTS\r\n\r\n# 인자 없을 때\r\ngh workflow run \"Daily Investment News Scraper\" --ref master\r\n```\r\n\r\n실행 디렉토리: 현재 프로젝트의 Git 레포지토리 루트 (`git rev-parse --show-toplevel`로 확인)\r\n\r\n### Step 2: 실행 대기 및 모니터링\r\n\r\n```bash\r\n# 10초 대기 후 상태 확인\r\nsleep 10\r\ngh run list --workflow=\"Daily Investment News Scraper\" --limit 1\r\n```\r\n\r\n- `in_progress`이면 완료될 때까지 30초 간격으로 재확인 (최대 5분)\r\n- `completed`이면 Step 3으로\r\n\r\n### Step 3: 결과 확인\r\n\r\n```bash\r\n# 최신 run ID로 결과 확인\r\ngh run view {RUN_ID}\r\n```\r\n\r\n- **success**: Step 4로 → 상세 로그 확인\r\n- **failure**: Step 5로 → 에러 분석\r\n\r\n### Step 4: 성공 시 상세 로그\r\n\r\n```bash\r\ngh run view {RUN_ID} --log 2>&1 | grep -E \"수집|저장|완료|기사|deal|0개|건|투자|❌|✅|⚠️\"\r\n```\r\n\r\n사용자에게 보고할 내용:\r\n- 수집된 기사 수\r\n- 저장된 건수\r\n- 탈락된 기사와 사유\r\n- 이메일 발송 여부\r\n\r\n### Step 5: 실패 시 에러 분석\r\n\r\n```bash\r\ngh run view {RUN_ID} --log-failed 2>&1 | grep -E \"error|Error|Traceback|TypeError|ModuleNotFoundError|exit code\" | head -20\r\n```\r\n\r\n에러 원인을 분석하고 사용자에게 보고:\r\n- 에러 종류 (스크립트 오류, 환경변수 누락, 의존성 문제 등)\r\n- 해당 코드 위치\r\n- 수정 방안 제안\r\n\r\n## 사용 예시\r\n\r\n```\r\n/deal-news              # 어제 날짜 뉴스 수집\r\n/deal-news 2026-01-30   # 특정 날짜 뉴스 수집\r\n```\r\n\r\n## 관련 파일\r\n\r\n- 워크플로우: `.github/workflows/daily-news-scraper.yml`\r\n- 수집 스크립트: `Valuation_Company/scripts/investment-news-scraper/daily_auto_collect.py`\r\n- 이메일 발송: `Valuation_Company/scripts/investment-news-scraper/send_daily_email.py`\r\n\r\n## 사전 준비 (이 스킬을 사용하기 전에)\r\n\r\n이 SKILL.md는 **실행 지시서**입니다. 아래 항목이 프로젝트에 먼저 준비되어 있어야 동작합니다.\r\n\r\n1. **GitHub Actions 워크플로우 파일**: `.github/workflows/daily-news-scraper.yml`을 프로젝트에 생성하세요. 뉴스를 수집하는 Python 스크립트를 실행하는 워크플로우입니다.\r\n2. **뉴스 수집 Python 스크립트**: 실제 뉴스를 크롤링/수집하는 스크립트를 작성하세요.\r\n3. **GitHub CLI (`gh`)**: 로컬에 설치되어 있어야 합니다. (`gh auth login`으로 인증 필요)\r\n4. **GitHub 레포지토리**: 프로젝트가 GitHub에 push되어 있어야 Actions가 동작합니다.\r\n\r\n위 파일들은 이 스킬에 포함되어 있지 않습니다. 자신의 프로젝트에 맞게 직접 구축한 후, 이 SKILL.md를 `.claude/skills/deal-news/SKILL.md`에 배치하면 `/deal-news` 명령으로 자동화할 수 있습니다.\r\n",
    "meta": {
      "id": "deal-news",
      "title": "Deal 뉴스 자동 수집",
      "icon": "📰",
      "category": "자동화",
      "description": "GitHub Actions로 투자 뉴스를 수집하고 결과를 확인하는 워크플로우 자동화 스킬"
    }
  },
  "youtube-generate": {
    "content": "---\nname: youtube-generate\ndescription: 유튜브 영상 올인원 생성 - 소재 파일 → 리서치 → 대본 → 재료 생성 → 블로그\nargument-hint: \"<소재파일경로>\"\nallowed-tools: \"Bash(python *), Read, AskUserQuestion\"\n---\n\n# YouTube 영상 올인원 자동화\n\n소재 파일 하나로 유튜브 영상 제작에 필요한 모든 재료를 자동 생성합니다.\n\n## 프로세스\n\n### Step 1: 경쟁 영상 리서치 (Gemini)\n\n소재와 유사한 인기 유튜브 영상을 자동 검색하고 대본/구조를 분석합니다.\n\n```bash\npython orchestrator.py --research $ARGUMENTS\n```\n\n실행 디렉토리: 현재 프로젝트의 Git 레포지토리 루트 (`git rev-parse --show-toplevel`로 확인)\n\n완료 후 사용자에게 보고:\n- 검색된 영상 수와 제목\n- 분석 결과 요약\n- output/research/[타임스탬프]/ 폴더 경로\n\n사용자에게 \"리서치 결과를 확인하셨나요? 대본 생성으로 넘어갈까요?\" 확인 후 Step 2로.\n\n### Step 2: 올인원 스크립트 생성 (Claude)\n\n소재 + Step 1 리서치 결과를 참고하여 제목, 썸네일 문구, 대본을 한 번에 생성합니다.\n\n```bash\npython orchestrator.py --write $ARGUMENTS\n```\n\n완료 후:\n1. 생성된 title.txt 내용을 사용자에게 보여주기\n2. 생성된 thumbnail.txt 내용을 사용자에게 보여주기\n3. 생성된 script.txt 내용을 사용자에게 보여주기\n4. **반드시** \"대본 내용이 괜찮으신가요? 수정할 부분이 있으면 말씀해주세요.\" 확인\n\n사용자가 수정 요청하면 script.txt를 수정합니다.\n사용자가 OK하면 Step 3으로.\n\n### Step 3: 영상 재료 생성\n\n확정된 대본으로 음성, 이미지 프롬프트, Vrew 가이드, 메타데이터를 자동 생성합니다.\n\n사용자에게 롱폼/숏폼 여부를 확인합니다.\n\n```bash\n# 롱폼\npython orchestrator.py output/scripts/[타임스탬프]/script.txt\n\n# 숏폼\npython orchestrator.py output/scripts/[타임스탬프]/script.txt --short\n```\n\n완료 후 사용자에게 보고:\n- 생성된 파일 목록 (음성, 이미지 프롬프트, 가이드, 메타데이터)\n- output 폴더 경로\n- \"Vrew에서 편집 후 유튜브에 업로드하세요. 업로드 후 블로그 글이 필요하면 유튜브 URL을 알려주세요.\"\n\n### Step 4: 블로그 글 생성 (선택)\n\n사용자가 유튜브 URL을 제공하면 블로그 글을 생성합니다.\n\n```bash\npython orchestrator.py --blog <유튜브URL> output/[Step3 폴더경로]\n```\n\n완료 후 사용자에게 보고:\n- 생성된 블로그 글 미리보기\n- 파일 경로\n\n## 사용 예시\n\n```\n/youtube-generate input/topic.txt\n/youtube-generate input/건강정보_소재.txt\n```\n\n## 관련 파일\n\n- 오케스트레이터: `orchestrator.py`\n- 경쟁 분석: `modules/competitor_analyzer.py`\n- 스크립트 생성: `modules/script_writer.py`\n- 음성 생성: `modules/voice_generator.py`\n- 이미지 프롬프트: `modules/prompt_generator.py`\n- Vrew 가이드: `modules/guide_generator.py`\n- 메타데이터: `modules/metadata_generator.py`\n- 블로그: `modules/blog_generator.py`\n- 설정: `config/settings.yaml`\n\n## 사전 준비 (이 스킬을 사용하기 전에)\n\n이 SKILL.md는 **실행 지시서**입니다. 아래 파일/환경이 프로젝트에 먼저 준비되어 있어야 동작합니다.\n\n1. **Python 프로젝트 구조**: 위 관련 파일 목록의 Python 파일들을 직접 구축해야 합니다.\n   - `orchestrator.py` - 전체 파이프라인을 조율하는 메인 스크립트\n   - `modules/` - 각 단계별 모듈 (리서치, 대본, 음성, 이미지, 블로그 등)\n   - `config/settings.yaml` - API 키, 모델 설정 등\n2. **Python 환경**: Python 3.x + 필요한 패키지 설치 (`pip install -r requirements.txt`)\n3. **외부 API 키**: 사용하는 AI 모델(Gemini, Claude 등)의 API 키 설정\n4. **Claude Code**: `.claude/skills/youtube-generate/SKILL.md`에 배치하면 `/youtube-generate` 명령 사용 가능\n\n위 파일들은 이 스킬에 포함되어 있지 않습니다. 이 스킬은 \"이미 구축된 YouTube 영상 자동화 프로젝트\"를 Claude Code에서 편리하게 실행하기 위한 명령 템플릿입니다. 자신의 프로젝트 구조에 맞게 명령어와 경로를 수정하여 사용하세요.\n",
    "meta": {
      "id": "youtube-generate",
      "title": "YouTube 영상 올인원 생성",
      "icon": "🎬",
      "category": "콘텐츠 제작",
      "description": "소재 파일 하나로 리서치 → 대본 → 음성/이미지/가이드 → 블로그까지 자동 생성"
    }
  }
};
